### ISSUE TITLE
Create requirements spreadsheet

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/DaSSCo-Transcription#4]
- [x] Use this template to capture requirements from first transcription workshop:  [Transcription requirements.xlsx](https://github.com/NHMDenmark/DaSSCo-Transcription/files/13307199/Transcription.requirements.xlsx)
- [x] Decide on how to categorise (and add as a tab to the spreadsheet) (Pip to help/do this bit)
- [ ] Categorise all requirements listed 
- [ ] Initial requirements should be reviewed and discussed (initially with Pip and Chelsea, and then with Bhupjit)
- [x] Finalise and send out (this needs to be co-ordinated with other documents)

Save spreadsheet in following location N:\SCI-SNM-DigitalCollections\DaSSCo\Transcription

**Due date: 11/01/2024**

**Comment by AstridBVW** [comment]
During the catch up meeting 20231205, it was decided to capture user stories from the workshop rather than requirements. A few requirements were mentioned during the workshop but mostly it was people sharing their experience with transcription as part of mass digitisation. 

The user stories are documented in this spreadsheet: 
[Workshop_20231107_User_stories.xlsx](https://github.com/NHMDenmark/DaSSCo-Transcription/files/13673205/Workshop_20231107_User_stories.xlsx)

The spreadsheet includes 3 sheets; User stories, Requirements, and Actions.

I have tried my best to sort the info captured from the notes correctly but in cases where I am wrong, the original sentence/wording from the notes is included for each so they can easily be re-sorted and re-written into something else.
I have also attempted to assign them a "category" from the overall process we discussed (select+retrieve, view, annotate etc.), it is in the new column "Category_overall process".

**Comment by PipBrewer** [comment]
@AstridBVW During our catch up meeting, we divided the transcription process into chunks. Let's use them as our categories in the spreadsheet. After that I think we can send out the spreadsheet as part of the transcription workshop results in January and then continue to work on this afterwards. 


[Workshop_20231107_User_stories(1).xlsx](https://github.com/NHMDenmark/DaSSCo-Transcription/files/13792884/Workshop_20231107_User_stories.1.xlsx)

**Comment by AstridBVW** [comment]
The spreadsheet was sent out 20240116.

It has been saved in the following location: 
N:\SCI-SNM-DigitalCollections\DaSSCo\Transcription\Workshop 1 November 2023\Reporting
